### ISSUE TITLE
Downloading Individual Sheets as CSV

### ISSUE THREAD

**Issue by marrowb** [asweigart/ezsheets#11]
Hi Al,

Big fan of your books. In _Automating the Boring Stuff_ , you reference downloading sheets other than the first one in the spreadsheet. I've been struggling to do so, even after I set the index attribute to something other than 0, like so:
```
ss=ezsheets.Spreadsheet('ID')
ss.index=2
ss.downloadAsCSV()
```
I find that this still just downloads the first sheet in the spreadsheet.

**Comment by marrowb** [comment]
After reading more closely, it seems like it is only possible to download the sheet at Index 0. So in order to download all sheets as CSV I would have to first temporarily switch all the sheets' indices to 0.

**Comment by asweigart** [comment]
Yeah, after looking at the Google Sheets API, I don't think they support a way to do this. I'll make a note about your workaround in the documentation. Thanks!
