### ISSUE TITLE
AttributeError: module 'ezsheets' has no attribute 'Spreadsheet'

### ISSUE THREAD

**Issue by willward1** [asweigart/ezsheets#4]
Python newbie here. I am trying to follow the quickstart guide. I get to the point of opening a sheet and am getting the error shown below.  Everything seemed to install correctly during the setup process and I have the credentials.json in the same directory. Any ideas?

**My code:**

> import ezsheets
> s = ezsheets.Spreadsheet('https://docs.google.com/spreadsheets/d/my-unique-id')

**Error message:**

>  Traceback (most recent call last):
>   File "dash_read.py", line 2, in <module>
>     s = ezsheets.Spreadsheet('https://docs.google.com/spreadsheets/d/my-unique-id')
> AttributeError: module 'ezsheets' has no attribute 'Spreadsheet'

**Comment by mwishoff** [comment]
Looks like version 0.0.1 is what pip is installing. The code is documented as version 0.0.2 though, could be an update that fixes it. In the repository if you import the package from the src directory level with the pickle and credentials.json in the directory it seems to work.

>>> import ezsheets
>>> m = ezsheets.Spreadsheet('https://docs.google.com/spreadsheets/d/10tRbpHZYkfRecHyRHRjBLdQYoq5QWNBqZmH9tt4Tjng/edit#gid=0')
>>> m.__str__()
'<Spreadsheet title="Untitled spreadsheet", 3 sheets>'

**Comment by willward1** [comment]
thanks! pip3 install ezsheets==0.0.2 is what worked for me
