### ISSUE TITLE
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by Scylla2020** [asweigart/ezsheets#9]
Im getting this error on trying to use ezsheets. I downloaded the credentials.json file and renamed it to credentials-sheets.json. However running import ezsheets doesn't do anything, no browser window opens and no pickle files are created, which I guess is the source of the error?

**Comment by asweigart** [comment]
I don't have enough information to reproduce this issue. Can you see if this still happens in the latest version of ezsheets? I'm going to close this issue for now unless I can reproduce it.

**Comment by dan-gheorghita** [comment]
#34 Solved here #34
